modLoader = "javafml" #mandatory
loaderVersion = "[40,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license = "MIT License"
[[mods]] #mandatory
modId = "createab" #mandatory
version = "${file.jarVersion}" #mandatory
logoFile="logo.png"
authors="StacheSebastian"
displayName = "CreateArmoredCopperBacktanks" #mandatory
description = '''
Adds armored Backtanks to Create
'''
[[dependencies.createab]] #optional
modId = "forge" #mandatory
mandatory = true #mandatory
versionRange = "[40,)" #mandatory
ordering = "NONE"
side = "BOTH"
[[dependencies.createab]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.2,1.19)"
ordering = "NONE"
side = "BOTH"
[[dependencies.createab]]
modId = "create"
mandatory = true
versionRange = "[0.5,)"
ordering = "NONE"
side = "BOTH"
